# ~/.zshrc
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="jonathan"

HIST_STAMPS="mm/dd/yyyy"
HISTSIZE=10000
SAVEHIST=10000
SHARE_HISTORY=0

# my :gun + cmd  gbk exec cmd
plugins=(zsh-syntax-highlighting sudo zsh_reload my git autojump)


source $ZSH/oh-my-zsh.sh

if [ ! $SSH_CONNECTION  ] ; then
export IP="127.0.0.1"
else
export IP=`echo $SSH_CONNECTION|awk '{print $3}'`
fi

# Example aliases
alias czsh="vi ~/.zshrc"
alias cvi="vi ~/.vimrc"
alias cls="clear"
alias doc="cd ~/Documents/rst/Scratch"
alias vi="vim"
alias grep="grep --color=auto"
alias -s html=vim # 在命令行直接输入后缀为 html 的文件名，会在 TextMate 中打开
alias -s rb=vim   # 在命令行直接输入 ruby 文件，会在 TextMate 中打开
alias -s js=vi
alias -s c=vi
alias -s java=vi
alias -s rst=vi
alias -s txt=vi
alias -s gz='tar -xzvf'
alias -s tgz='tar -xzvf'
alias -s zip='unzip'
alias -s bz2='tar -xjvf'

#macdown 打开md
alias -s md=vi
alias -s c=vi
alias -s cpp=vi
alias -s h=vi

# FileSearch
function f() { find . -iname "*$1*" ${@:2} }
function r() { grep "$1" ${@:2} -n -R  . }

#mkdir and cd
function mkcd() { mkdir -p "$@" && cd "$_"; }

# Aliases
alias cppcompile='c++ -std=c++11 -stdlib=libc++'

setopt nonomatch

export PATH="/usr/local/sbin:$PATH"
